import os
from dotenv import load_dotenv

load_dotenv()

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

DATABASE_URL = os.environ['DATABASE_URL']
DATABASE_MAX_POOL = int(os.environ.get('DATABASE_MAX_POOL', 5))
DATABASE_MAX_OVERFLOW = int(os.environ.get('DATABASE_MAX_OVERFLOW', 5))

REDIRECT_HOST_NAME = os.environ.get('REDIRECT_HOST_NAME', 'http://127.0.0.1:8000')

os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'

GOOGLE_SSO_CLIENT_ID = os.environ['GOOGLE_SSO_CLIENT_ID']
GOOGLE_SSO_CLIENT_SECRET = os.environ['GOOGLE_SSO_CLIENT_SECRET']
GOOGLE_CALLBACK = f'{REDIRECT_HOST_NAME}/auth/google/callback'

REFRESH_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7
ACCESS_TOKEN_EXPIRE_MINUTES = 30

JWT_SECRET_KEY = os.environ['JWT_SECRET_KEY']
JWT_REFRESH_SECRET_KEY = os.environ['JWT_REFRESH_SECRET_KEY']
ALGORITHM = 'HS256'
