name: Deploy
on:
   workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_IP }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: sudo docker compose -f /home/tiazz0/faml/docker-compose.yaml pull && sudo docker compose -f /home/tiazz0/faml/docker-compose.yaml up -d
      
