name: Docker Image CI
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    steps:
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Fittercup
      uses: docker/login-action@v2
      with:
          registry: docker.fittercup.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and export to Docker
      uses: docker/build-push-action@v4
      with:
          push: true
          tags: docker.fittercup.com/imajity-worker:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
